# Generated by Django 5.1.3 on 2024-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pollapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
